### ISSUE TITLE
Ability to customize state param (for redirecting a user to the original URL after login)

### ISSUE THREAD

**Issue by aaronshaf** [sergiodxa/remix-auth-oauth2#1]
At `let state = this.generateState();` one could store some [custom state](https://medium.com/@guillaume.viguierjust/oauth-2-redirecting-a-user-to-the-original-url-after-login-dd1e264b4157) or the current pathname.

**Comment by shamsup** [comment]
According to [Google](https://developers.google.com/identity/protocols/oauth2/openid-connect#createxsrftoken) and [auth0](https://auth0.com/docs/configure/attack-protection/state-parameters), the best practice for the `state` param in OAuth2 is using a CSRF token instead of guessable parameters. You can store any other custom information in the session itself.
